# Generated by Django 5.1.1 on 2024-10-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_score_gardenbox_delete_plantgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenbox',
            name='plant_image',
        ),
    ]
