# Generated by Django 5.1.1 on 2024-10-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_gardenbox_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenbox',
            name='plant_image',
            field=models.ImageField(default='default_plant.png', upload_to='plant_images/'),
        ),
    ]
