# Generated by Django 5.1 on 2025-07-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_dark_mode_profile_email_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badge',
        ),
    ]
