# Generated by Django 5.1.1 on 2024-10-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gardenbox_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenbox',
            name='plant_image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
