# Generated by Django 5.1.1 on 2024-10-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gardenbox_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenbox',
            name='plant_image',
            field=models.ImageField(blank=True, null=True, upload_to='garden_images'),
        ),
    ]
