# Generated by Django 5.1.1 on 2024-10-26 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gardenbox_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenbox',
            name='plant_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='garden_images'),
            preserve_default=False,
        ),
    ]
